### ISSUE TITLE
ALE Support

### ISSUE THREAD

**Issue by MarcelRobitaille** [aars/syntastic-platformio#1]
Thanks for the plugin. Is there any way to get this to work with ALE?

**Comment by aars** [comment]
I have never heard of ALE before this. So I wouldn't know.

But all this plugin does is read some variables from a file, and sets them as the appropriate vars in VIM.

I've done a quick scan but can't find any gcc options to set in ALE (at all, am I missing something?)

Looking at [this file](https://github.com/w0rp/ale/blob/master/ale_linters/cpp/gcc.vim) you might just have to set  that `gcc_cpp_options`.
